// Builds tests/CU_COMPARISON.md from the Anchor baseline
// (tests/CU_BASELINE.md) and the pinocchio run
// (tests/CU_BASELINE.pinocchio.md). Run via `pnpm cu:compare`.
import { readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

function parseTable(file) {
  const rows = new Map();
  for (const line of readFileSync(path.join(ROOT, file), "utf8").split("\n")) {
    const m = line.match(/^\|\s*([a-z_() ]+?)\s*\|\s*(\d+)\s*\|$/);
    if (m) rows.set(m[1], Number(m[2]));
  }
  if (rows.size === 0) throw new Error(`no CU rows parsed from ${file}`);
  return rows;
}

const anchor = parseTable("tests/CU_BASELINE.md");
const pino = parseTable("tests/CU_BASELINE.pinocchio.md");

const names = [...anchor.keys()];
const rows = names.map((name) => {
  const a = anchor.get(name);
  const p = pino.get(name);
  if (p === undefined) return { name, a, p: null, delta: null, pct: null };
  return { name, a, p, delta: p - a, pct: ((p - a) / a) * 100 };
});

const w = (s, n, right = false) =>
  right ? String(s).padStart(n) : String(s).padEnd(n);
const nameW = Math.max("Instruction".length, ...rows.map((r) => r.name.length));

const lines = [
  "# Anchor vs Pinocchio — Compute-Unit Comparison",
  "",
  "Generated by `pnpm cu:compare` from `tests/CU_BASELINE.md` (Anchor) and",
  "`tests/CU_BASELINE.pinocchio.md` (pinocchio), both measured with the same",
  "LiteSVM harness (`tests/cu-measurement.ts`).",
  "",
  `| ${w("Instruction", nameW)} | ${w("Anchor CU", 9, true)} | ${w("Pinocchio CU", 12, true)} | ${w("Δ", 8, true)} | ${w("Δ %", 7, true)} |`,
  `| ${"-".repeat(nameW)} | ${"-".repeat(8)}: | ${"-".repeat(11)}: | ${"-".repeat(7)}: | ${"-".repeat(6)}: |`,
  ...rows.map((r) =>
    r.p === null
      ? `| ${w(r.name, nameW)} | ${w(r.a, 9, true)} | ${w("n/a", 12, true)} | ${w("", 8, true)} | ${w("", 7, true)} |`
      : `| ${w(r.name, nameW)} | ${w(r.a, 9, true)} | ${w(r.p, 12, true)} | ${w(r.delta, 8, true)} | ${w(r.pct.toFixed(1) + "%", 7, true)} |`
  ),
  "",
];

const measured = rows.filter((r) => r.p !== null);
const totalA = measured.reduce((s, r) => s + r.a, 0);
const totalP = measured.reduce((s, r) => s + r.p, 0);
lines.push(
  `**Totals (measured rows): Anchor ${totalA} CU → Pinocchio ${totalP} CU ` +
    `(${(((totalP - totalA) / totalA) * 100).toFixed(1)}%).**`,
  ""
);

writeFileSync(path.join(ROOT, "tests/CU_COMPARISON.md"), lines.join("\n"));
console.log(`Wrote tests/CU_COMPARISON.md (${measured.length} rows compared)`);
