import { MockCourse } from "@/types";

export const mockCourses: MockCourse[] = [
  {
    id: "solana-101",
    title: "Solana Fundamentals",
    description:
      "Master the core concepts of Solana blockchain. Learn about accounts, transactions, programs, and the Solana programming model from the ground up.",
    difficulty: 1,
    duration: "4 hours",
    lessons: 12,
    xp: 1200,
    track: "Solana Fundamentals",
    trackId: 1,
    image: "/courses/solana-101.png",
    tags: ["Solana", "Blockchain", "Beginner"],
    instructor: "Superteam Brazil",
    enrolled: 1240,
    rating: 4.9,
  },
  {
    id: "anchor-101",
    title: "Anchor Framework Basics",
    description:
      "Build your first Solana programs using the Anchor framework. Cover PDAs, CPIs, and account validation with hands-on projects.",
    difficulty: 2,
    duration: "6 hours",
    lessons: 15,
    xp: 1800,
    track: "Anchor Development",
    trackId: 2,
    image: "/courses/anchor-101.png",
    tags: ["Anchor", "Rust", "Programs"],
    instructor: "Superteam Brazil",
    enrolled: 890,
    rating: 4.8,
  },
  {
    id: "defi-101",
    title: "DeFi on Solana",
    description:
      "Understand and build DeFi protocols on Solana. Learn AMMs, liquidity pools, yield farming, and token economics.",
    difficulty: 3,
    duration: "8 hours",
    lessons: 20,
    xp: 2500,
    track: "DeFi Development",
    trackId: 3,
    image: "/courses/defi-101.png",
    tags: ["DeFi", "AMM", "Advanced"],
    instructor: "Superteam Brazil",
    enrolled: 567,
    rating: 4.7,
  },
  {
    id: "nft-101",
    title: "NFTs & Metaplex Core",
    description:
      "Create and manage NFT collections using Metaplex Core. Build soulbound tokens, dynamic NFTs, and NFT marketplaces.",
    difficulty: 2,
    duration: "5 hours",
    lessons: 14,
    xp: 1600,
    track: "NFT Development",
    trackId: 4,
    image: "/courses/nft-101.png",
    tags: ["NFT", "Metaplex", "Token-2022"],
    instructor: "Superteam Brazil",
    enrolled: 723,
    rating: 4.8,
  },
  {
    id: "security-101",
    title: "Solana Security & Auditing",
    description:
      "Learn to identify and fix common Solana vulnerabilities. Master account validation, arithmetic overflow, and CPI security.",
    difficulty: 3,
    duration: "7 hours",
    lessons: 18,
    xp: 2200,
    track: "Security & Auditing",
    trackId: 5,
    image: "/courses/security-101.png",
    tags: ["Security", "Auditing", "Advanced"],
    instructor: "Superteam Brazil",
    enrolled: 445,
    rating: 4.9,
  },
  {
    id: "token-2022",
    title: "Token-2022 Extensions",
    description:
      "Deep dive into Token-2022 extensions. Build tokens with transfer hooks, confidential transfers, and permanent delegates.",
    difficulty: 2,
    duration: "5 hours",
    lessons: 13,
    xp: 1500,
    track: "Anchor Development",
    trackId: 2,
    image: "/courses/token-2022.png",
    tags: ["Token-2022", "Extensions", "Intermediate"],
    instructor: "Superteam Brazil",
    enrolled: 612,
    rating: 4.7,
  },
];

export const mockAchievements = [
  {
    id: "first-steps",
    name: "First Steps",
    description: "Complete your first lesson",
    icon: "🎯",
    xpReward: 50,
  },
  {
    id: "course-completer",
    name: "Course Completer",
    description: "Complete your first course",
    icon: "🏆",
    xpReward: 200,
  },
  {
    id: "week-warrior",
    name: "Week Warrior",
    description: "Maintain a 7-day streak",
    icon: "🔥",
    xpReward: 100,
  },
  {
    id: "rust-rookie",
    name: "Rust Rookie",
    description: "Complete first Anchor course",
    icon: "⚙️",
    xpReward: 150,
  },
  {
    id: "early-adopter",
    name: "Early Adopter",
    description: "Join during beta launch",
    icon: "⭐",
    xpReward: 500,
  },
  {
    id: "perfect-score",
    name: "Perfect Score",
    description: "Complete a course with 100% on all challenges",
    icon: "💎",
    xpReward: 300,
  },
];

export const mockLeaderboard = [
  { wallet: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU", xp: 15420, level: 12, rank: 1 },
  { wallet: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM", xp: 12800, level: 11, rank: 2 },
  { wallet: "3FZbgi29cpjq2GjdwV8eyHuJJnkLtktZc5K3RnVRcH3q", xp: 11200, level: 10, rank: 3 },
  { wallet: "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1", xp: 9800, level: 9, rank: 4 },
  { wallet: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263", xp: 8900, level: 9, rank: 5 },
  { wallet: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", xp: 7600, level: 8, rank: 6 },
  { wallet: "4k3Dyjzvzp8eMZWZ16pBV5EGoaXPALBmY1LnhEQoYrD8", xp: 6500, level: 8, rank: 7 },
  { wallet: "So11111111111111111111111111111111111111112", xp: 5400, level: 7, rank: 8 },
  { wallet: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB", xp: 4200, level: 6, rank: 9 },
  { wallet: "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So", xp: 3100, level: 5, rank: 10 },
];