import createMiddleware from 'next-intl/middleware';
import { updateSession } from '@/lib/supabase/proxy'
import { type NextRequest } from 'next/server'

const i18nMiddleware = createMiddleware({
  // A list of all locales that are supported
  locales: ['en', 'pt', 'es'],

  // Used when no locale matches
  defaultLocale: 'en',
  
  // Always use a prefix for the locale (e.g. /en/about)
  localePrefix: 'always'
});

export default async function proxy(request: NextRequest) {
  // First update the supabase session and keep any cookie mutations.
  const sessionResponse = await updateSession(request);

  // Preserve redirects generated by session logic.
  if (sessionResponse.status >= 300 && sessionResponse.status < 400) {
    return sessionResponse;
  }

  // Then run the i18n middleware.
  const i18nResponse = i18nMiddleware(request);

  // Copy Supabase auth cookies to the final response to keep session in sync.
  sessionResponse.cookies.getAll().forEach(({ name, value, ...options }) => {
    i18nResponse.cookies.set(name, value, options as any);
  });

  return i18nResponse;
}

export const config = {
  // Match only internationalized pathnames
  matcher: [
    '/',
    '/(pt|es|en)/:path*',
    '/((?!api|_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)'
  ]
};
