#!/usr/bin/env tsx
/**
 * compile-content.ts — compile the courses-academy content repo (pinned in
 * content.lock) into a committed, typed JSON bundle under src/content/generated.
 *
 * Pipeline: fetch tarball at the locked SHA → extract → delegate to the pure
 * `compileBundle` (src/lib/content/compile/compile-bundle.ts — Zod-validate every
 * doc fail-closed, project via the SAME projector the content sync uses, emit
 * deterministic JSON) → write the result to disk. CI recompiles and `git diff
 * --exit-code`s the result, so `compileBundle`'s output MUST be a pure function
 * of the input tree: stable key order, no wall-clock timestamps (meta.compiledAt
 * is the locked commit's own date), assets left as repo-relative paths.
 *
 * The executor gate (§6.2a: solution passes / starter fails) is NOT re-run here.
 * It requires the live QuickJS/rust/build runners, was already enforced by the
 * courses-academy CI gate that made this SHA mergeable, and the sync itself
 * defers rust/buildable. Compile is a projection step, not a re-certification.
 *
 *   Run from apps/web:  pnpm compile-content   (or: pnpm tsx scripts/compile-content.ts)
 *   Optional GITHUB_TOKEN raises the GitHub rate limit.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  compileBundle,
  compileContent,
  ASSET_PUBLIC_PREFIX,
  type CompiledBundle,
} from "../src/lib/content/compile/compile-bundle";
import { extractTarball } from "../src/lib/content/compile/tarball";
import { ContentValidationError } from "../src/lib/content/compile/types";

export { compileBundle, compileContent };

// ── GitHub fetch (local, no server-only deps) ────────────────────────────────

interface Lock {
  repo: string;
  sha: string;
}

function githubHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    "User-Agent": "superteam-academy-compile-content",
    Accept: "application/vnd.github+json",
  };
  if (process.env.GITHUB_TOKEN)
    headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  return headers;
}

/** Small retry — the local DNS here is flaky; a commit SHA's bytes never change. */
async function fetchWithRetry(
  url: string,
  init: RequestInit,
  attempts = 4
): Promise<Response> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url, init);
      if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
      return res;
    } catch (e) {
      lastErr = e;
      if (i < attempts - 1)
        await new Promise((r) => setTimeout(r, 500 * (i + 1)));
    }
  }
  throw new Error(
    `GitHub request failed after ${attempts} attempts (${url}): ${String(lastErr)}`
  );
}

async function fetchTarball(lock: Lock): Promise<Uint8Array> {
  const url = `https://api.github.com/repos/${lock.repo}/tarball/${lock.sha}`;
  const res = await fetchWithRetry(url, {
    headers: githubHeaders(),
    redirect: "follow",
  });
  return new Uint8Array(await res.arrayBuffer());
}

/** The locked commit's own committer date — deterministic per SHA, never wall-clock. */
async function fetchCommitDate(lock: Lock): Promise<string> {
  const url = `https://api.github.com/repos/${lock.repo}/commits/${lock.sha}`;
  const res = await fetchWithRetry(url, { headers: githubHeaders() });
  const body = (await res.json()) as {
    commit?: { committer?: { date?: string } };
  };
  const date = body.commit?.committer?.date;
  if (!date) throw new Error(`commit ${lock.sha} has no committer date`);
  return date;
}

// ── CLI ──────────────────────────────────────────────────────────────────────

const README = `# Generated content bundle

Generated by \`scripts/compile-content.ts\` (\`pnpm compile-content\`) from the
courses-academy repo pinned in \`apps/web/content.lock\`. **Do not hand-edit** —
CI recompiles and \`git diff --exit-code\`s this directory to enforce freshness.
`;

/**
 * Write a compiled bundle to disk, rebuilding BOTH the generated dir and the
 * asset dir from scratch so a stray committed file (a removed module, a renamed
 * image) never survives a recompile — that would leave `git status` clean while
 * the tree no longer matches the compiler output, punching a hole in the CI
 * freshness guarantee. Safe because the compiler always emits every module +
 * README. When there are no assets the asset dir is left absent.
 */
export function writeBundle(
  dirs: { outDir: string; assetsDir: string },
  bundle: CompiledBundle
): void {
  fs.rmSync(dirs.outDir, { recursive: true, force: true });
  fs.mkdirSync(dirs.outDir, { recursive: true });
  fs.writeFileSync(path.join(dirs.outDir, "README.md"), README);
  for (const [name, contents] of bundle.files) {
    fs.writeFileSync(path.join(dirs.outDir, name), contents);
  }

  fs.rmSync(dirs.assetsDir, { recursive: true, force: true });
  for (const [rel, bytes] of bundle.assets) {
    const dest = path.join(dirs.assetsDir, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, bytes);
  }
}

async function main(): Promise<void> {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const lockPath = path.resolve(here, "../content.lock");
  const outDir = path.resolve(here, "../src/content/generated");
  const assetsDir = path.resolve(here, "../public/", ASSET_PUBLIC_PREFIX);

  const lock = JSON.parse(fs.readFileSync(lockPath, "utf8")) as Lock;
  console.log(`Compiling ${lock.repo}@${lock.sha}`);

  const [tarball, compiledAt] = await Promise.all([
    fetchTarball(lock),
    fetchCommitDate(lock),
  ]);
  const tree = await extractTarball(tarball);
  const { files, assets } = compileBundle(tree, { sha: lock.sha, compiledAt });

  writeBundle({ outDir, assetsDir }, { files, assets });

  const counts = (
    JSON.parse(files.get("meta.json")!) as { counts: Record<string, number> }
  ).counts;
  console.log(
    `Emitted ${files.size} modules to ${path.relative(process.cwd(), outDir)}`
  );
  console.log(`Counts: ${JSON.stringify(counts)}`);
  console.log(
    assets.size === 0
      ? "Assets: none"
      : `Assets: ${assets.size} file(s) → ${path.relative(process.cwd(), assetsDir)}`
  );
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main().catch((err: unknown) => {
    if (err instanceof ContentValidationError) {
      console.error(
        `Content validation failed (${err.issues.length} issue(s)):`
      );
      for (const issue of err.issues) console.error(issue);
    } else {
      console.error(err);
    }
    process.exit(1);
  });
}
