export const leaderboardUsers = [
  {
    id: 1,
    rank: 1,
    name: 'Jordan Chen',
    avatar: '👨‍💻',
    xp: 120,
    level: 1,
    streak: 1,
    course: 'Solana Fundamentals',
    isCurrentUser: false,
  },
  {
    id: 2,
    rank: 2,
    name: 'Alex Rivera',
    avatar: '👨‍🎓',
    xp: 100,
    level: 1,
    streak: 1,
    course: 'Anchor Framework',
    isCurrentUser: false,
  },
  {
    id: 3,
    rank: 3,
    name: 'Sam Patel',
    avatar: '👩‍💻',
    xp: 100,
    level: 1,
    streak: 1,
    course: 'DeFi on Solana',
    isCurrentUser: false,
  },
  {
    id: 4,
    rank: 4,
    name: 'Morgan Lee',
    avatar: '👩‍🎓',
    xp: 100,
    level: 1,
    streak: 1,
    course: 'Solana Fundamentals',
    isCurrentUser: false,
  },
  {
    id: 5,
    rank: 5,
    name: 'Casey Williams',
    avatar: '👨‍💼',
    xp: 100,
    level: 1,
    streak: 1,
    course: 'NFT Development',
    isCurrentUser: false,
  },
  // {
  //   id: 6,
  //   rank: 6,
  //   name: 'Taylor Brown',
  //   avatar: '👩‍💼',
  //   xp: 8650,
  //   level: 9,
  //   streak: 12,
  //   course: 'Anchor Framework',
  //   isCurrentUser: false,
  // },
  // {
  //   id: 7,
  //   rank: 7,
  //   name: 'Jordan Martinez',
  //   avatar: '👨‍🔬',
  //   xp: 8200,
  //   level: 8,
  //   streak: 3,
  //   course: 'Solana Fundamentals',
  //   isCurrentUser: false,
  // },
  // {
  //   id: 8,
  //   rank: 8,
  //   name: 'Riley Anderson',
  //   avatar: '👩‍🔬',
  //   xp: 7890,
  //   level: 8,
  //   streak: 7,
  //   course: 'DeFi on Solana',
  //   isCurrentUser: false,
  // },
  // {
  //   id: 9,
  //   rank: 9,
  //   name: 'Alex Thompson',
  //   avatar: '👨‍🏫',
  //   xp: 7450,
  //   level: 7,
  //   streak: 2,
  //   course: 'Cross-Program Invocations',
  //   isCurrentUser: false,
  // },
  // {
  //   id: 10,
  //   rank: 10,
  //   name: 'Jordan Garcia',
  //   avatar: '👩‍🏫',
  //   xp: 7100,
  //   level: 7,
  //   streak: 10,
  //   course: 'NFT Development',
  //   isCurrentUser: false,
  // },
]

export const courses = [
  'All Courses',
  'Solana Fundamentals',
  'Anchor Framework',
  'DeFi on Solana',
  'NFT Development',
  'Cross-Program Invocations',
]

export const timeFilters = [
  { label: 'Weekly', value: 'weekly' },
  { label: 'Monthly', value: 'monthly' },
  { label: 'All Time', value: 'all-time' },
]
