import { Program, AnchorProvider } from "@coral-xyz/anchor";
import { PROGRAM_ID } from "./constants";

// The IDL and its TypeScript type are generated by `anchor build`.
// Copy or symlink the output from:
//   onchain-academy/target/idl/onchain_academy.json
//   onchain-academy/target/types/onchain_academy.ts
// into app/src/lib/solana/idl/ before building the frontend.
import type { OnchainAcademy } from "./idl/onchain_academy";
import IDL from "./idl/onchain_academy.json";

/**
 * Creates a typed Anchor Program instance bound to the given provider.
 * The provider must be constructed from a wallet adapter connection, e.g.:
 *
 *   const connection = new Connection(DEVNET_RPC_URL, "confirmed");
 *   const provider = new AnchorProvider(connection, wallet, {});
 *   const program = getProgram(provider);
 */
export function getProgram(provider: AnchorProvider): Program<OnchainAcademy> {
  return new Program<OnchainAcademy>(
    IDL as OnchainAcademy,
    PROGRAM_ID,
    provider
  );
}
