import type { LucideIcon } from 'lucide-react';
import {
  Anchor,
  Award,
  BookOpen,
  Brain,
  Bug,
  CheckCircle2,
  Circle,
  Code2,
  Coins,
  CreditCard,
  Crown,
  Flame,
  GraduationCap,
  Hash,
  Palette,
  Rocket,
  Shield,
  Sparkles,
  Sprout,
  Star,
  Sunrise,
  Target,
  TrendingUp,
  Trophy,
  User,
  Users,
  Wrench,
  Zap,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  '👣': Target,
  '📚': BookOpen,
  '🎓': GraduationCap,
  '🧠': Brain,
  '🏆': Trophy,
  '🎯': Target,
  '⚡': Zap,
  '🔥': Flame,
  '🌟': Star,
  '⭐': Star,
  '👑': Crown,
  '🦀': Code2,
  '⚓': Anchor,
  '🚀': Rocket,
  '🌅': Sunrise,
  '💯': CheckCircle2,
  '🐛': Bug,
  '⚔️': Shield,
  '💻': Code2,
  '💎': Trophy,
  '🏅': Award,
  '💫': Sparkles,
  '📈': TrendingUp,
  '🔟': Hash,
  '🎖️': Award,
  '🌱': Sprout,
  '💳': CreditCard,
  '🎨': Palette,
  '💰': Coins,
  '🛠️': Wrench,
  '🔷': Circle,
  target: Target,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  brain: Brain,
  trophy: Trophy,
  zap: Zap,
  flame: Flame,
  star: Star,
  crown: Crown,
  anchor: Anchor,
  rocket: Rocket,
  sunrise: Sunrise,
  bug: Bug,
  shield: Shield,
  code: Code2,
  award: Award,
  trending: TrendingUp,
  sprout: Sprout,
  'credit-card': CreditCard,
  palette: Palette,
  coins: Coins,
  wrench: Wrench,
  user: User,
  users: Users,
};

export function getLucideIcon(icon?: string): LucideIcon {
  if (!icon) return Trophy;
  return ICON_MAP[icon] || Trophy;
}
