import {
  FixedToolbarFeature,
  InlineToolbarFeature,
  HeadingFeature,
  BoldFeature,
  ItalicFeature,
  UnderlineFeature,
  StrikethroughFeature,
  SubscriptFeature,
  SuperscriptFeature,
  InlineCodeFeature,
  AlignFeature,
  IndentFeature,
  OrderedListFeature,
  UnorderedListFeature,
  ChecklistFeature,
  BlockquoteFeature,
  LinkFeature,
  HorizontalRuleFeature,
  BlocksFeature,
  CodeBlock,
} from "@payloadcms/richtext-lexical";

export const richTextFeatures = [
  FixedToolbarFeature(),
  InlineToolbarFeature(),
  HeadingFeature({ enabledHeadingSizes: ["h1", "h2", "h3"] }),
  BoldFeature(),
  ItalicFeature(),
  UnderlineFeature(),
  StrikethroughFeature(),
  SubscriptFeature(),
  SuperscriptFeature(),
  InlineCodeFeature(),
  AlignFeature(),
  IndentFeature(),
  OrderedListFeature(),
  UnorderedListFeature(),
  ChecklistFeature(),
  BlockquoteFeature(),
  LinkFeature(),
  HorizontalRuleFeature(),
  BlocksFeature({ blocks: [CodeBlock()] }),
];

export const promptFeatures = [
  FixedToolbarFeature(),
  InlineToolbarFeature(),
  HeadingFeature({ enabledHeadingSizes: ["h2", "h3"] }),
  BoldFeature(),
  ItalicFeature(),
  InlineCodeFeature(),
  OrderedListFeature(),
  UnorderedListFeature(),
  BlocksFeature({ blocks: [CodeBlock()] }),
];
