/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    courses: Course;
    modules: Module;
    lessons: Lesson;
    'lesson-contents': LessonContent;
    reviews: Review;
    streaks: Streak;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    'lesson-contents': LessonContentsSelect<false> | LessonContentsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    streaks: StreaksSelect<false> | StreaksSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es' | 'pt-br') | ('en' | 'es' | 'pt-br')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es' | 'pt-br';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Better Auth user ID — links to auth system
   */
  betterAuthId?: string | null;
  /**
   * Whether the user has completed onboarding
   */
  onboardingComplete?: boolean | null;
  /**
   * Solana wallet public key
   */
  walletAddress?: string | null;
  authMethod?: ('wallet' | 'google' | 'github') | null;
  /**
   * Unique username (lowercase, letters/numbers/underscores)
   */
  username?: string | null;
  displayName?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  role?: ('learner' | 'instructor' | 'admin') | null;
  socialLinks?: {
    github?: string | null;
    twitter?: string | null;
    website?: string | null;
  };
  locale?: ('en' | 'pt-br' | 'es') | null;
  isPublicProfile?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left blank
   */
  slug?: string | null;
  description: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  /**
   * e.g. "8 hours"
   */
  duration?: string | null;
  /**
   * Computed and updated by seed script
   */
  totalLessons?: number | null;
  /**
   * Total XP earnable for completing this course
   */
  xpReward: number;
  /**
   * e.g. "Core", "DeFi", "Security", "NFTs"
   */
  topic?: string | null;
  thumbnail?: (number | null) | Media;
  learningOutcomes?:
    | {
        outcome: string;
        id?: string | null;
      }[]
    | null;
  prerequisites?:
    | {
        prerequisite: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Number of enrolled learners (seeded + live count)
   */
  enrollmentCount?: number | null;
  /**
   * Average rating (0–5, 1 decimal)
   */
  rating?: number | null;
  /**
   * Total number of ratings submitted
   */
  ratingCount?: number | null;
  /**
   * Human-readable update date, e.g. "Feb 2025"
   */
  lastUpdated?: string | null;
  /**
   * Primary content language
   */
  language?: string | null;
  /**
   * Maps to on-chain track ID
   */
  trackId?: number | null;
  /**
   * Level within the track
   */
  trackLevel?: number | null;
  /**
   * Course PDA seed (e.g. "anchor-101")
   */
  onChainCourseId?: string | null;
  instructor?: (number | null) | User;
  status?: ('draft' | 'published') | null;
  certificate?: boolean | null;
  onChainCredential?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  title: string;
  course: number | Course;
  /**
   * Order within the course (0, 1, 2…)
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  module: number | Module;
  type: 'video' | 'reading' | 'code_challenge' | 'quiz' | 'hybrid';
  /**
   * e.g. "15 min"
   */
  duration?: string | null;
  xpReward: number;
  /**
   * Order within the module (0, 1, 2…)
   */
  sortOrder: number;
  /**
   * Maps to the bitmap index in on-chain Enrollment
   */
  onChainLessonIndex?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-contents".
 */
export interface LessonContent {
  id: number;
  lesson: number | Lesson;
  /**
   * Ordered content blocks — mix markdown, video, and callouts
   */
  blocks?:
    | {
        blockType: 'markdown' | 'video' | 'callout';
        /**
         * Markdown content or callout text
         */
        content?: string | null;
        /**
         * Video embed URL
         */
        url?: string | null;
        videoTitle?: string | null;
        calloutVariant?: ('info' | 'warning' | 'tip') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Code challenge config (optional)
   */
  challenge?: {
    prompt?: string | null;
    objectives?:
      | {
          objective: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Pre-populated code for the challenge
     */
    starterCode?: string | null;
    language?: ('rust' | 'typescript' | 'json') | null;
    testCases?:
      | {
          name: string;
          expected: string;
          id?: string | null;
        }[]
      | null;
    expectedOutput?: string | null;
    /**
     * Reference solution
     */
    solutionCode?: string | null;
  };
  /**
   * Quiz config (optional)
   */
  quiz?: {
    questions?:
      | {
          questionType: 'radio' | 'checkbox' | 'code';
          prompt: string;
          options?:
            | {
                option: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Zero-based index of correct answer (radio)
           */
          correctIndex?: number | null;
          /**
           * Array of zero-based correct indices (checkbox)
           */
          correctIndices?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          starterCode?: string | null;
          language?: string | null;
          /**
           * Expected code output
           */
          expected?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  hints?:
    | {
        hint: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Solution explanation or code
   */
  solution?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  course: number | Course;
  user?: (number | null) | User;
  /**
   * Display name for seeded or anonymous reviews
   */
  reviewerName?: string | null;
  rating: number;
  text: string;
  /**
   * Human-readable date for seeded reviews (e.g. "2 weeks ago")
   */
  displayDate?: string | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streaks".
 */
export interface Streak {
  id: number;
  user: number | User;
  currentStreak?: number | null;
  longestStreak?: number | null;
  lastActivityDate?: string | null;
  /**
   * Array of { date: string, active: boolean } for calendar visualization
   */
  history?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'lesson-contents';
        value: number | LessonContent;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'streaks';
        value: number | Streak;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  betterAuthId?: T;
  onboardingComplete?: T;
  walletAddress?: T;
  authMethod?: T;
  username?: T;
  displayName?: T;
  avatar?: T;
  bio?: T;
  role?: T;
  socialLinks?:
    | T
    | {
        github?: T;
        twitter?: T;
        website?: T;
      };
  locale?: T;
  isPublicProfile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  longDescription?: T;
  difficulty?: T;
  duration?: T;
  totalLessons?: T;
  xpReward?: T;
  topic?: T;
  thumbnail?: T;
  learningOutcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  prerequisites?:
    | T
    | {
        prerequisite?: T;
        id?: T;
      };
  enrollmentCount?: T;
  rating?: T;
  ratingCount?: T;
  lastUpdated?: T;
  language?: T;
  trackId?: T;
  trackLevel?: T;
  onChainCourseId?: T;
  instructor?: T;
  status?: T;
  certificate?: T;
  onChainCredential?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  course?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  module?: T;
  type?: T;
  duration?: T;
  xpReward?: T;
  sortOrder?: T;
  onChainLessonIndex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-contents_select".
 */
export interface LessonContentsSelect<T extends boolean = true> {
  lesson?: T;
  blocks?:
    | T
    | {
        blockType?: T;
        content?: T;
        url?: T;
        videoTitle?: T;
        calloutVariant?: T;
        id?: T;
      };
  challenge?:
    | T
    | {
        prompt?: T;
        objectives?:
          | T
          | {
              objective?: T;
              id?: T;
            };
        starterCode?: T;
        language?: T;
        testCases?:
          | T
          | {
              name?: T;
              expected?: T;
              id?: T;
            };
        expectedOutput?: T;
        solutionCode?: T;
      };
  quiz?:
    | T
    | {
        questions?:
          | T
          | {
              questionType?: T;
              prompt?: T;
              options?:
                | T
                | {
                    option?: T;
                    id?: T;
                  };
              correctIndex?: T;
              correctIndices?: T;
              starterCode?: T;
              language?: T;
              expected?: T;
              id?: T;
            };
      };
  hints?:
    | T
    | {
        hint?: T;
        id?: T;
      };
  solution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  course?: T;
  user?: T;
  reviewerName?: T;
  rating?: T;
  text?: T;
  displayDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streaks_select".
 */
export interface StreaksSelect<T extends boolean = true> {
  user?: T;
  currentStreak?: T;
  longestStreak?: T;
  lastActivityDate?: T;
  history?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}